### ISSUE TITLE
Possible Changes

### ISSUE THREAD

**Issue by andreymatin** [andreymatin/scss-reset#12]
- ? mixins: responsive video 

- [ ] doc: how to use total scss with web components

- ? `contain: content` for blocks with dynamical content, lists, scroll containers, modals (? `<dialog>`), sidebars (? `<aside>`)

- ? RTL test
- ? L/RTL experiments with logical CSS like
```css
.example {
  margin-block: 0;
  margin-inline: 0;
  padding-block: 0;
  padding-inline: 0;
}

table {
...
  text-align: start;
}

input {
...
  margin-inline: 0;
  padding-inline: 0;
}
```

- test: page with separated section to test default browser styles 

- ? tighter layout and control the spacing between elements + test page/section
```css
:where(body, h1, h2, h3, h4, h5, h6, p, figure, figcaption, blockquote, dl, dd, ul, ol, li, input, button, textarea, select, table, th, td, pre, code, hr, fieldset, legend) {
  margin-block-end: 0;
}
```

- ? test: `<dialog>` test section
- ? test: different JS frameworks
- ? test: tilewind test page

- ? default `text-wrap: balance;` for header tags or/and for `[class*="title"]`

- ? defaul p `{  text-wrap: pretty; }` - for paragraph

- ? security: disable SVG foreignObject (HTML injection)
```css
foreignObject {
  all: unset;
  display: none;
}
```

- ? add:

```css
[draggable="true"] {
  -webkit-user-drag: element;
}
```

- ? modal dialogs:

```css
:where(html:has(dialog:modal[open])) {
    overflow: clip;
}
```

+

```css
dialog {
  background-color: transparent;
  border: none;
  display: flex;
  margin: 0;
  padding: 0;
  position: fixed;
}

dialog:not([open]) {
  display: none;
}

dialog::backdrop {
  background-color: rgba(0, 0, 0, 0.5);
}
```

- ? add:

```css
:where(p, h1, h2, h3, h4, h5, h6) {
  overflow-wrap: break-word;
}
```

- ? add:

```css
img {
  object-fit: cover;
  object-position: center;
  aspect-ratio: attr(width) / attr(height);
}

img[width][height] {
  height: auto;
}
```

- ? add: 

```css
:root {
  color-scheme: light dark;
  forced-color-adjust: none;
}
```

- ? add:

```css
html {
  scrollbar-gutter: stable;
  scroll-padding-top: 2rem;
  
  @media (prefers-reduced-motion: no-preference) {
    scroll-behavior: smooth;
  }
}
```

- ? remove: 

```css
button {
  border: 0;
  background: transparent;
}
```

- [x] update test templates
- [x] --save-dev installation instructions
- [x] sys: remove *.lock
- [x] css support + CDN
- [x] total reset

- ? additional hidden:

```css
:where([hidden]:not([hidden='until-found'])) {
?    display: none !important;
```

- ? additional typographical features

```css
:where(html) {
    -webkit-text-size-adjust: none;
    color-scheme: dark light;
    tab-size: 2;
    scrollbar-gutter: stable;
    interpolate-size: allow-keywords;
...
```

- ? @media print for snippets
- ? html, body { -webkit-overflow-scrolling: touch;
- ? `body { text-rendering: optimizeSpeed; ... ` => `html { text-rendering: optimizeLegibility; ... `
- ? `isolation: isolate;` for React and for typography utils (`.isolate`)
- ? diff view for ports
- ?  examples for structured elements wrapped by mixins and extended by variables
- ? select reset for dropdown component by mixins
- ?  ``` html {  scroll-behavior: smooth; } ```
- ? plugin: inverted styles etc.
- ? scss-typography
- ? Relocate outdated reset styles into mixins (? should be done by autoprefix)
- ? [less](https://www.npmjs.com/package/less-plugin-sass2less), ? stylus ports
- ? test: additional test cases for popular js libraries (sandbox)
- ? scss config by condition variables for enabling normalization features
- ? example for postcss ( or plugin )
- ? doc: link to https://gitter.im/frontent-issues/community
- ? test: override reset styles by custom (a (:hover, :visited etc.), input)
- ? doc: features and secondary (more detailed) features
